import { TPlaylist, TTrack } from "@/types";
import { auth, clerkClient } from "@clerk/nextjs/server";

const BASE_URL = "https://api.spotify.com/v1";

export async function createPlaylist(
  playlist: TPlaylist,
  userId: string
): Promise<string | undefined> {
  const accessToken = await getAccessToken();
  const url = `${BASE_URL}/users/${userId}/playlists`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({
      name: "AI Generated Playlist",
      description: "Playlist generated by the plailist app",
      public: false,
    }),
  });

  if (response.status !== 201) return undefined;
  const playlistResponse = await response.json();

  const trackUris = playlist.map((track) => track.uri);
  const tracksAdded = await addTracksToPlaylist(
    playlistResponse.id,
    trackUris,
    accessToken
  );

  if (tracksAdded) {
    return playlistResponse.external_urls.spotify;
  }
}

export async function addTracksToPlaylist(
  playlistId: string,
  trackUris: string[],
  accessToken: string
) {
  const url = `${BASE_URL}/playlists/${playlistId}/tracks`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({
      uris: trackUris,
    }),
  });

  return response.status === 201;
}

export async function lookupSong({
  artist,
  title,
  accessToken,
}: {
  artist: string;
  title: string;
  accessToken: string;
}): Promise<TTrack | null> {
  const urlEncodedArtist = encodeURIComponent(artist);
  const urlEncodedTitle = encodeURIComponent(title);

  const url = `${BASE_URL}/search?&type=track&q=artist:${urlEncodedArtist}%20track:${urlEncodedTitle}&limit=1`;

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  const data = await response.json();

  if (data.tracks.items && data.tracks.items.length > 0) {
    const track = data.tracks.items[0];

    return {
      artist: track.artists[0].name,
      name: track.name,
      album: track.album.name,
      uri: track.uri,
      images: track.album.images,
      duration: track.duration_ms,
      popularity: track.popularity,
    };
  }

  return null;
}

export async function getAccessToken() {
  const { userId } = await auth();

  if (!userId) throw new Error("User not authenticated");

  const clerk = await clerkClient();
  const clerkResponse = await clerk.users.getUserOauthAccessToken(
    userId,
    "oauth_spotify"
  );

  const accessToken = clerkResponse.data[0].token || "";

  if (!accessToken) throw new Error("Failed to get access token");

  return accessToken;
}
