import { TPlaylist, TTrack } from "@/types";
import { auth } from "../../../auth";

const BASE_URL = "https://api.spotify.com/v1";

export async function createPlaylist(
  playlist: TPlaylist
): Promise<string | undefined> {
  const session = await auth();
  // @ts-ignore
  const accessToken = session?.user?.access_token;
  // @ts-ignore
  const userId = session?.user?.user_id;
  const url = `${BASE_URL}/users/${userId}/playlists`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({
      name: "AI Generated Playlist",
      description: "Playlist generated by the plailist app",
      public: false,
    }),
  });

  if (response.status !== 201) return undefined;
  const playlistResponse = await response.json();

  const trackUris = playlist.map((track) => track.uri);
  const tracksAdded = await addTracksToPlaylist(playlistResponse.id, trackUris);

  if (tracksAdded) {
    return playlistResponse.external_urls.spotify;
  }
}

export async function addTracksToPlaylist(
  playlistId: string,
  trackUris: string[]
) {
  const session = await auth();
  // @ts-ignore
  const accessToken = session?.user?.access_token;
  const url = `${BASE_URL}/playlists/${playlistId}/tracks`;
  const response = await fetch(url, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
    body: JSON.stringify({
      uris: trackUris,
    }),
  });

  return response.status === 201;
}

export async function lookupSong({
  artist,
  title,
}: {
  artist: string;
  title: string;
}): Promise<TTrack | null> {
  const session = await auth();
  // @ts-ignore
  const accessToken = session?.user?.access_token;
  const urlEncodedArtist = encodeURIComponent(artist);
  const urlEncodedTitle = encodeURIComponent(title);

  const url = `${BASE_URL}/search?&type=track&q=artist:${urlEncodedArtist}%20track:${urlEncodedTitle}&limit=1`;

  const response = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  const data = await response.json();

  if (data.tracks.items && data.tracks.items.length > 0) {
    const track = data.tracks.items[0];

    return {
      artist: track.artists[0].name,
      name: track.name,
      album: track.album.name,
      uri: track.uri,
      images: track.album.images,
      duration: track.duration_ms,
      popularity: track.popularity,
    };
  }

  return null;
}
